image: Visual Studio 2017

version: '{build}-{branch}'
environment:
  ASSEMBLY_VERSION: 1.0.0

before_build:
  - dotnet restore

configuration: Release
platform: Any CPU

nuget:
  account_feed: true

artifacts:
- path: '**\*.nupkg'
  name: NuGet

branches:
  only:
    - master